### ISSUE TITLE
Fails to build with Qt 6.10: call of overloaded ‘Set(QByteArray, google::protobuf::Arena*)’ is ambiguous

### ISSUE THREAD

**Issue by khumba** [pokerth/pokerth#489]
Hi,

I'm getting the following error when building the stable branch on Gentoo (Qt 6.10.1, Protobuf 31.1).  QByteArray has implicit conversions to `const char *` and also since Qt 6.10 `std::string_view` ([1]; if that's the same as abseil's string_view), so maybe we need to disambiguate?

[1] https://doc.qt.io/qt-6/qbytearray.html

    In file included from /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/chatcleaner/cleanerserver.cpp:38:
    /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/third_party/protobuf/chatcleaner.pb.h: In instantiation of ‘void CleanerChatReplyMessage::set_cleanertext(Arg_&&, Args_ ...) [with Arg_ = QByteArray; Args_ = {}]’:
    /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/chatcleaner/cleanerserver.cpp:198:29:   required from here
      198 |                         netReply->set_cleanertext(checkMessage.toUtf8());
          |                         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
    /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/third_party/protobuf/chatcleaner.pb.h:2025:26: error: call of overloaded ‘Set(QByteArray, google::protobuf::Arena*)’ is ambiguous
     2025 |   _impl_.cleanertext_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
          |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/third_party/protobuf/chatcleaner.pb.h:2025:26: note: there are 6 candidates
    In file included from /var/tmp/portage/games-board/pokerth-2.0_pre20260124/work/pokerth-db15ec119390d9dc0617440c3515cc6df2890aa7/src/third_party/protobuf/chatcleaner.pb.h:22:
    /usr/include/google/protobuf/arenastring.h:294:8: note: candidate 1: ‘void google::protobuf::internal::ArenaStringPtr::Set(absl::lts_20250512::string_view, google::protobuf::Arena*)’
      294 |   void Set(absl::string_view value, Arena* arena);
          |        ^~~
    /usr/include/google/protobuf/arenastring.h:464:13: note: candidate 2: ‘void google::protobuf::internal::ArenaStringPtr::Set(const char*, google::protobuf::Arena*)’
      464 | inline void ArenaStringPtr::Set(const char* s, Arena* arena) {
          |             ^~~~~~~~~~~~~~

Thanks!

**Comment by kphilipp-inq** [comment]
Hi,

currently we strongly recommend using Qt 6.9.2 LTS - see INSTALL.

If you find a fix for it - as it seems only to be about chatcleaner, please send a pull request. Qt 6.10. will be used earliest after new release.

Thank you.

**Comment by q4z1** [comment]
I updated Changelog, to make clear that current code is for Qt6.9.2 LTS.

**Comment by q4z1** [comment]
Thx a lot for PR with a fix!

**Comment by khumba** [comment]
Great, thanks so much for the quick response!
