### ISSUE TITLE
fails to build with boost 1.87

### ISSUE THREAD

**Issue by david-geiger** [pokerth/pokerth#439]
Hi,

On Mageia Cauldron pokerth fails to build with latest boost 1.87.0 with the following build issue:

> src/db/serverdbfactory.h:47:70: error: 'io_service' is not a member of 'boost::asio'; did you mean 'use_service'?
   47 |                 ServerDBCallback &cb, boost::shared_ptr<boost::asio::io_service> ioService) = 0;
      |                                                                      ^~~~~~~~~~
      |                                                                      use_service
src/db/serverdbfactory.h:47:80: error: template argument 1 is invalid
   47 |                 ServerDBCallback &cb, boost::shared_ptr<boost::asio::io_service> ioService) = 0;
      |                                                                                ^
make[1]: *** [Makefile.pokerth_db:368: obj/serverdbfactory.o] Error 1
make[1]: Leaving directory '/home/iurt/rpmbuild/BUILD/pokerth-1.1.2-build/pokerth-1.1.2-rc'
make[1]: *** Waiting for unfinished jobs....

Attached full build log:

[build.x86_64.0.20250209154023.log](https://github.com/user-attachments/files/18764148/build.x86_64.0.20250209154023.log)

**Comment by Ponce** [comment]
Can confirm this too on slackware64-current trying to build latest git master
```
Info: creating stash file /tmp/SBo/pokerth-20250118_60b7f75/.qmake.stash
( test -e Makefile.pokerth_protocol || /usr/bin/qmake-qt5 -o Makefile.pokerth_protocol /tmp/SBo/pokerth-20250118_60b7f75/pokerth_protocol.pro QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ ) && make -f Makefile.pokerth_protocol 
make[1]: Entering directory '/tmp/SBo/pokerth-20250118_60b7f75'
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -fPIC -fPIC -Wall -Wextra -frtti -D_REENTRANT -DENABLE_IPV6 -DQT_NO_DEBUG -I. -I. -Isrc -I/include -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/pokerth.pb.o src/third_party/protobuf/pokerth.pb.cc
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -fPIC -fPIC -Wall -Wextra -frtti -D_REENTRANT -DENABLE_IPV6 -DQT_NO_DEBUG -I. -I. -Isrc -I/include -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/chatcleaner.pb.o src/third_party/protobuf/chatcleaner.pb.cc
rm -f lib/libpokerth_protocol.a
ar cqs lib/libpokerth_protocol.a obj/pokerth.pb.o obj/chatcleaner.pb.o
make[1]: Leaving directory '/tmp/SBo/pokerth-20250118_60b7f75'
( test -e Makefile.pokerth_db || /usr/bin/qmake-qt5 -o Makefile.pokerth_db /tmp/SBo/pokerth-20250118_60b7f75/pokerth_db.pro QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ ) && make -f Makefile.pokerth_db 
make[1]: Entering directory '/tmp/SBo/pokerth-20250118_60b7f75'
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -fPIC -fPIC -Wall -Wextra -frtti -D_REENTRANT -DENABLE_IPV6 -DTIXML_USE_STL -DQT_NO_DEBUG -I. -I. -Isrc -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/serverdbcallback.o src/db/common/serverdbcallback.cpp
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -fPIC -fPIC -Wall -Wextra -frtti -D_REENTRANT -DENABLE_IPV6 -DTIXML_USE_STL -DQT_NO_DEBUG -I. -I. -Isrc -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/serverdbfactory.o src/db/common/serverdbfactory.cpp
In file included from src/db/common/serverdbfactory.cpp:32:
src/db/serverdbfactory.h:47:70: error: ‘io_service’ is not a member of ‘boost::asio’; did you mean ‘use_service’?
   47 |                 ServerDBCallback &cb, boost::shared_ptr<boost::asio::io_service> ioService) = 0;
      |                                                                      ^~~~~~~~~~
      |                                                                      use_service
src/db/serverdbfactory.h:47:80: error: template argument 1 is invalid
   47 |                 ServerDBCallback &cb, boost::shared_ptr<boost::asio::io_service> ioService) = 0;
      |                                                                                ^
make[1]: *** [Makefile.pokerth_db:1223: obj/serverdbfactory.o] Error 1
make[1]: Leaving directory '/tmp/SBo/pokerth-20250118_60b7f75'
make: *** [Makefile:77: sub-pokerth_db-pro-make_first-ordered] Error 2
```

**Comment by benoliver999** [comment]
Yep same thing on Arch Linux. The package maintainer is looking for help over there with this but I'm way out of my depth

https://aur.archlinux.org/packages/pokerth

**Comment by Hains** [comment]
You can try to this repo for test
https://github.com/Hains/pokerth/tree/boost-187

With thanks to amini-allight for updating websocketpp.

I ported pokerth to Qt6 as well.
Run:
```
export QTDIR=/usr/lib/qt6
export PATH=$QTDIR/bin:$PATH
```
before runing qmake pokerth.pro to build pokerth against Qt6.

Tested with Kubuntu 25.04 (beta) with Boost 1.87 built from source as the distro still on 1.83.

Feel free to cherry-pick or send Pull requests.

**Comment by jlocash2** [comment]
> You can try to this repo for test https://github.com/Hains/pokerth/tree/boost-187

It builds fine with Qt5 or 6 for me.

I didn't notice any issues playing a local game.

However, online play doesn't work.
When logging in I get a popup window titled "Connect to Server" which says starting session and the task bar stops at 80%. It times out and then I get "The connection to the server was lost." It happens when logging in as a registered user or guest.

**Comment by q4z1** [comment]
@Hains @jlocash2 : 

Can you please assist and describe the build way - including your pkglist (with `dbpkg -l`)?

I am not using kubuntu - instead I am using a docker image of plucky with distrobox on my nixos system:

* I installed all other deps with `apt build-dep pokerth`
* I manually built and installed boost 1.87 (https://www.linuxfromscratch.org/blfs/view/git/general/boost.html)
* I installed qt6-base-dev, qt6-svg-dev and qt6-declarative-dev as I saw "qml-client" in the pro file

I tried both: `qmake CONFIG+="client" -spec linux-g++ pokerth.pro` and `qmake CONFIG+="qml-client" -spec linux-g++ pokerth.pro`

Both `make` runs result in errors.

**Comment by Hains** [comment]
> > You can try to this repo for test https://github.com/Hains/pokerth/tree/boost-187
> 
> > 
> However, online play doesn't work. When logging in I get a popup window titled "Connect to Server" which says starting session and the task bar stops at 80%. It times out and then I get "The connection to the server was lost." It happens when logging in as a registered user or guest.

That is a problem from the master branch. 
I build a new branch base on the stable branch. Problem with network server solved.

stable-boost187 branch.
https://github.com/Hains/pokerth/commits/stable-boost187/


@q4z1 
Can you try new branch as well?  Dockerfile updated.
I have no experience with Docker, image sorry.
Can you post the error, so we have more information at least.

**Comment by jlocash2** [comment]
> That is a problem from the master branch. I build a new branch base on the stable branch. Problem with network server solved.
> 
> stable-boost187 branch. https://github.com/Hains/pokerth/commits/stable-boost187/

Thanks, that works for me now.

@q4z1 
I build my systems from source so I can't help you with a dpkg -l.
I use this patch for fixing linking issues with newer abseil releases:
```
diff -Nuarp pokerth-git.orig/pokerth_game.pro pokerth-git/pokerth_game.pro
--- pokerth-git.orig/pokerth_game.pro   2024-12-03 17:49:25.000000000 -0500
+++ pokerth-git/pokerth_game.pro        2024-12-04 15:54:27.554088120 -0500
@@ -524,7 +524,10 @@ unix:!mac {
                kFreeBSD = $$find(UNAME, "kFreeBSD")
                LIBS += -lsqlite3 \
                                -ltinyxml \
-                               -lprotobuf
+                               -lprotobuf \
+                               -labsl_log_internal_message \
+                               -labsl_log_internal_check_op \
+                               -labsl_log_internal_nullguard
                LIBS += $$BOOST_LIBS
                LIBS += -lSDL \
                                -lSDL_mixer \
```
I use `qmake CONFIG+="client" DEFINES+="BOOST_BIND_GLOBAL_PLACEHOLDERS" QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ pokerth.pro` when building.

But as @Hains mentioned, error messages would help.

**Comment by q4z1** [comment]
@Hains : Iam already using your branch.
@Hains @jlocash2 : Thank you. I think I solved it now by purging/uninstalling the installed boost-1.83  version, which was installed by apt build-dep. Then I re-installed the 1.87 version from source and it seems to compile through now.

 ... the error messages were related to boost ofc ;-)

**Comment by q4z1** [comment]
Compilation of qml-client was successful but now it complains about qt6 Stuff like `qrc:/main.qml:2:1: module "QtQuick.Controls" version 1.3 is not installed` when I launch the binary `pokerth_qml-client`.

@Hains Which qt6 version do you use? On my plucky system it's 6.8.2 (kubuntu 25.04 propably uses the same ubuntu debs).

**Comment by Hains** [comment]
Yes 6.8.2.

**Comment by q4z1** [comment]
Ok ... I expect you are using the ubuntu qt6 libs. Can you provide a `dpkg -l|grep qt6` (and just in case: `dpkg -l|grep qt5`)?

In parrallel I am trying to use the official download qt variant - just to be sure.

I'm really curious to see the client running with qt6 qml ;-)

**Comment by Hains** [comment]
Text file attached.

[dpkg.txt](https://github.com/user-attachments/files/19514105/dpkg.txt)

Qt5

[dpkg-qt5.txt](https://github.com/user-attachments/files/19514135/dpkg-qt5.txt)

**Comment by Hains** [comment]
![Image](https://github.com/user-attachments/assets/79bccfc7-049c-4c05-945a-67c815ac146b)

Danuxi table

![Image](https://github.com/user-attachments/assets/5efdcb82-8f94-480d-b7b0-0620b8bbc551)

**Comment by Hains** [comment]
Qt6, brown window border instead of gray.
Resizing main window is a bit tricky.
With Qt 6.8.2 background image of server list not shown (pokerth.png). 
With Qt 6.6.2 it is there.

**Comment by q4z1** [comment]
I'm not sure how direct pm contact works here in git - can we get in touch by email? Send an email to webmaster@pokerth.net - I will catch you there.

I played a lot with qt6 and qml ... already having a new gui for the client. I really would like to merge my efforts with yours.

**Comment by q4z1** [comment]
Closing because the boost issue got fixed and the rest is more related to qt. Merge into stable will follow soon.

**Comment by Hains** [comment]
E-mail send.

**Comment by q4z1** [comment]
Merged into stable. Thank you very much Hains.

**Comment by q4z1** [comment]
> E-mail send.

I replied with my private gmail address. Did you receive my mails?

**Comment by Hains** [comment]
Yes, received and replied.
But return with 'mail delivery failed returning message to sender' error.
